name: RobDomenech
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.10330060822889209
  lightness: 0.3933918357361108
  saturation: 0
  rhythmicContrast: 0.2755146536510438
purpose: []
